= Fedora Silverblue Einführung

Wilkommen in der Silverblue Benutzereinführung!

image::silverblue-logo.svg[Silverblue logo]

_Fedora Silverblue_ ist ein unveränderliches Desktop-Betriebssystem. Es zielt darauf ab 
extrem stabil und verlässlich zu sein. Auch will es eine herausragende Plattform für 
Entwickler sein, und für jene welche Container-fokussierte Workflows benutzen.

[[introduction]]
== Heranführung zu Silverblue

Silverblue ist eine spezielle Variante von Fedora Workstation. Es schaut aus, fühlt sich so an und verhält sich wie 
ein normales Desktop-Betriebssystem, auch die Erfahrung, die du machst ist gleich der, 
die du auch mit dem normalen Fedora Workstation machst.

Wie auch immer, anders als andere Betriebssysteme, ist Silverblue unveränderlich. Das bedeuted 
das jede Installation Installation von Silverblue ist identisch zu jeder anderen Installation der selben
Version. Das Betriebssystem,das auf deiner Festplatte ist genau die gleiche, 
wie auf jeder anderen Maschine, und die Benutzung verändert sich nie.

Silverblue's unveränderliches Design macht it stabiler, weniger fehleranfällig 
und einfacher zu testen und zu entwickeln. Schlussendlich sorgt Silverblue's unveränderliches 
Design auch dafür die perfekte Plattform für Containerisierte Apps 
und Containerbasierte Software zu entwickeln. In jedem Fall 
werden Apps und Container getrennt vom Host-System gehalten, 
dass sorgt für Stabilität und Verlässlichkeit.

Silverblue's core technologies have some other helpful features. OS updates are 
fast and there's no waiting around for them to install: just reboot as normal 
to start using the next version. With Silverblue, it is also possible to roll 
back to the previous version of the operating system, if something goes wrong.

[[this-guide]]
== Über diese Einführung

In den meisten Teilen verhält sich Silverblue wie eine 
Standard-Fedora-Workstation-Installation und die https://docs.fedoraproject.org/[Standard-Fedora-Dokumentation] 
kann dazu verwendet werden. Diese Anleitung behandelt nur jene Bereiche von Silverblue, 
die sich vom normalen Fedora Workstation unterscheidet, 
dazu gehört:

* link:installation[Das Installieren des Betriebssystems]
* link:getting-started[Das Installieren von Apps und Software]
* link:updates-upgrades-rollbacks[Die Betriebssystem-Upgrades und -Rücksprünge]

Die Zielgruppe für diese Einführung sind neue Nutzer, von welchen nicht erwartet wird 
spezielle Kenntnisse oder technisches Wissen über Silverblue's Struktur zu haben. 
Trotzdem werden hier einige Hintergünde zur link:technical-information[technischen Dokumentation] zur Verfügung gestellt,
für alle Interessierten und die die mehr darüber lernen wollen.
