= Fedora Silverblue User Guide

Wilkommen in der Silverblue Benutzereinführung!

image::silverblue-logo.svg[Silverblue logo]

_Fedora Silverblue_ ist ein unveränderliches Desktop-Betriebssystem. Es zielt darauf ab 
extrem stabil und verlässlich zu sein. Auch will es eine herausragende Plattform für 
Entwickler sein, und für jene welche Container-fokussierte Workflows benutzen.

[[introduction]]
== Heranführung zu Silverblue

Silverblue ist eine Variante von Fedora Workstation. Es schaut aus, fühlt sich so an und verhält sich wie 
ein normales Desktop-Betriebssystem, auch die Erfahrung, die du machst ist gleich der, 
die du auch mit dem normalen Fedora Workstation machst.

Wie auch immer, anders als andere Betriebssysteme, ist Silverblue unveränderlich. Das bedeuted 
das jede Installation Installation von Silverblue ist identisch zu jeder anderen Installation der selben
Version. Das Betriebssystem,das auf deiner Festplatte ist genau die gleiche, 
wie auf jeder anderen Maschine, und die Benutzung verändert sich nie.

Silverblue's immutable design is intended to make it more stable, less prone to 
bugs, and easier to test and develop. Finally, Silverblue's immutable design 
also makes it an excellent platform for containerized apps as well as 
container-based software development. In each case, apps and 
containers are kept separate from the host system, improving stability and 
reliability.

Silverblue's core technologies have some other helpful features. OS updates are 
fast and there's no waiting around for them to install: just reboot as normal 
to start using the next version. With Silverblue, it is also possible to roll 
back to the previous version of the operating system, if something goes wrong.

[[this-guide]]
== About this guide

In most cases, Silverblue behaves like a standard Fedora Workstation 
installation, and the https://docs.fedoraproject.org/[standard Fedora 
documentation] can be used. This guide covers those areas where Silverblue 
differs from a standard Fedora Workstation, including:

* link:installation[OS installation]
* link:getting-started[Installing apps and software]
* link:updates-upgrades-rollbacks[OS upgrades and rollbacks]

The primary audience for these docs are new users, who aren't expected to have 
specialist knowledge or technical knowledge about Silverblue's internals. 
However, some background link:technical-information[technical information] is 
provided, for those who are interested and want to learn more.
